---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by never.
--- DateTime: 2021/10/22 10:23
---
local cjson = require("cjson");

local function read_file(path)
    local file = io.open(path, "rb") -- r read mode and b binary mode
    if not file then return nil end
    local content = file:read "*a" -- *a or *all reads the whole file
    file:close()
    return content
end
print("Lua Hello World!")

local function a()
    print("run created")

    local tLt = LuaType.New()



    local fileContent = read_file("element.json");
--     tLt.a = fileContent;
    local x = cjson.decode(fileContent);
--     tLt.x = x;

    cjson.encode(x);
    local xxx = GetTestInstance();
--     xxx.TestStr = fileContent;

--     local xxa = GetTestInstance();
--         xxa.TestStr = "fileContent";
--     print(xxx.TestStr);

end

local function b()
    print("run destroy")
end

RegisterCreated(a)

RegisterBeforeDestroy(b)






